import Navbar from "./navbar";

import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Add script tag for animejs */}
      {/* <Script src="/node_modules/animejs/lib/anime.min.js"></Script> */}
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
